version: '3'
services:
  jenkins:
    container_name: jenkins-ocean
    image: ec277c7b6df0
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net:
